apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
  labels:
    app: contract-processing-system
    component: backend
    version: v1
    managed-by: manual
    environment: ${ENV}
  annotations:
    # Secret rotation periods documented for automated rotation
    secret.kubernetes.io/rotation-period-secret-key: "90d"
    secret.kubernetes.io/rotation-period-mongodb: "90d"
    secret.kubernetes.io/rotation-period-redis: "90d"
    secret.kubernetes.io/rotation-period-aws: "90d"
    secret.kubernetes.io/rotation-period-google: "365d"
    secret.kubernetes.io/rotation-period-smtp: "180d"
    # Security annotations
    vault.hashicorp.com/agent-inject: "true"
    encryption.kubernetes.io/provider: "aes-256"
type: Opaque
data:
  # JWT signing key for authentication tokens
  # Rotation: 90 days
  SECRET_KEY: ${BASE64_SECRET_KEY}

  # MongoDB connection string with credentials
  # Rotation: 90 days
  # Format: mongodb+srv://username:password@host:port/database
  MONGODB_URL: ${BASE64_MONGODB_URL}

  # Redis authentication password
  # Rotation: 90 days
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}

  # AWS credentials for S3 and other services
  # Rotation: 90 days
  AWS_ACCESS_KEY_ID: ${BASE64_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_AWS_SECRET_ACCESS_KEY}

  # Google Vision API service account credentials
  # Rotation: 365 days
  # Contains JSON key file for service account
  GOOGLE_VISION_CREDENTIALS: ${BASE64_GOOGLE_VISION_CREDENTIALS}

  # SMTP credentials for email notifications
  # Rotation: 180 days
  SMTP_USER: ${BASE64_SMTP_USER}
  SMTP_PASSWORD: ${BASE64_SMTP_PASSWORD}

# Note: All values should be base64 encoded before being added to this file
# Example encoding: echo -n "value" | base64
# The ${BASE64_*} placeholders should be replaced with actual base64-encoded values
# during deployment through secure CI/CD processes or HashiCorp Vault integration